# This is a Docker Compose file for defining and running multi-container Docker applications.
# The version specifies the Compose file format version.
# 
# Services:
# - breezeicecast2: This service uses the 'breezeicecast2' image.
#   - build: Specifies the build configuration for the service.
#     - context: The build context, which is the directory containing the Dockerfile.
#     - dockerfile: The path to the Dockerfile used to build the image.
version: '3.4'

services:
  audio-server:
    image: audio-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ICECAST_SOURCE_PASSWORD=your_source_password
      - ICECAST_ADMIN_PASSWORD=your_admin_password
      - ICECAST_RELAY_PASSWORD=your_relay_password
      - ICECAST_ADMIN_USERNAME=admin
      - ICECAST_ADMIN_EMAIL=admin@example.com
      - ICECAST_LOCATION=Your Location
      - ICECAST_HOSTNAME=localhost
      - ICECAST_MAX_CLIENTS=100
      - ICECAST_MAX_SOURCES=2
